0-hreadelf: 0.c
	$gcc -Wall -Werror -Wextra -pedantic 0.c -o 0-hreadelf

1-hreadelf:  1.c
	$gcc -Wall -Werror -Wextra -pedantic  1.c -o 1-hreadelf
2-hreadelf: 2.c
	$gcc -Wall -Werror -Wextra -pedantic 2.c -o 2-hreadelf

100-hreadelf: 100.c
	$gcc -Wall -Werror -Wextra -pedantic 100.c -o 100-hreadelf